# ./docker/Dockerfile.web - v1.0.0
FROM node:20-alpine

WORKDIR /app

# Use a tiny static server
RUN npm i -g http-server@14

COPY ./src/web /app/src/web

EXPOSE 8080

CMD ["http-server", "src/web", "-p", "8080", "-c-1"]
# EOF ./docker/Dockerfile.web - v1.0.0
# 修正履歴:
# - 2025-10-20 v1.0.0: 初版作成
