# ./config/default.yaml - v1.0.0
app:
  env: dev
  data_dir: /app/data
  log_level: INFO
  plugins_dir: src/api/plugins
server:
  host: 0.0.0.0
  port: 8000
  allow_origins: ["*"]
llm:
  provider: openai
  model: gpt-4o-mini
  temperature: 0.2
runtime:
  mock_mode: true
# EOF ./config/default.yaml - v1.0.0
# 修正履歴:
# - 2025-10-20 v1.0.0: 初版作成